name: Generate TikTok Content

on:
  schedule:
    - cron: '0 8,14,20 * * *'
  workflow_dispatch:

jobs:
  generate-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create directories
        run: |
          mkdir -p images output quotes
          # If you don't have any images yet, create a sample one
          if [ ! -f "images/sample_dark_bg.jpg" ]; then
            python -c "from PIL import Image; Image.new('RGB', (1080, 1920), color=(20, 20, 30)).save('images/sample_dark_bg.jpg')"
          fi
          # If you don't have quotes.txt, create it
          if [ ! -f "quotes/quotes.txt" ]; then
            echo "Don't stop when you're tired, stop when you're done." > quotes/quotes.txt
            echo "Success is not final, failure is not fatal: it is the courage to continue that counts." >> quotes/quotes.txt
            echo "The only way to do great work is to love what you do." >> quotes/quotes.txt
          fi

      - name: Generate TikTok content
        run: python pipeline.py -n 3

      - name: List output files
        run: ls -la output/

      - name: Upload generated images
        uses: actions/upload-artifact@v3
        with:
          name: tiktok-posts
          path: output/*.jpg
          if-no-files-found: warn
          retention-days: 7

      - name: Commit and push generated images
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add output/*.jpg || echo "No images to add"
          git commit -m "Add generated TikTok posts" || echo "No changes to commit"
          git push || echo "Nothing to push"
